emit:
  - "@typespec/openapi3"
  - "@typespec/http-client-python"
  - "@typespec/http-client-java"
  - "@typespec/http-client-csharp"
  - "@typespec/http-client-js"
  - "@typespec/http-server-csharp"
options:
  "@typespec/openapi3":
    emitter-output-dir: "{output-dir}/{emitter-name}"
  "@typespec/http-client-python":
    emitter-output-dir: "{output-dir}/{emitter-name}"
  "@typespec/http-client-java":
    emitter-output-dir: "{output-dir}/{emitter-name}"
  "@typespec/http-client-csharp":
    emitter-output-dir: "{output-dir}/{emitter-name}"
  "@typespec/http-client-js":
    emitter-output-dir: "{output-dir}/{emitter-name}"
  "@typespec/http-server-csharp":
    emitter-output-dir: "{output-dir}/{emitter-name}"
