jobs:
- job: RunElectronUITestsOnLinux_1_CreateTypespecProject
  pool:
    vmImage: "ubuntu-latest"

  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: "20.18.3"
      displayName: "Install Node.js"

    - script: |
        sudo apt-get update
        sudo apt-get install -y \
          imagemagick x11-xserver-utils xdotool
      displayName: "Install Linux Dependencies"

    - script: |
        export DISPLAY=:99
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        echo ">>> Started xvfb"
      displayName: "Start xvfb and Set DISPLAY"

    - script: |
        mkdir -p images-linux
      displayName: "Ensure images-linux directory exists"
      
    - script: |
        npm install
        node -e "require('@vscode/test-electron').download().then(p => console.log('##vso[task.setvariable variable=VSCODE_E2E_DOWNLOAD_PATH]' + p))"
        sudo snap install code --classic
      displayName: "Install deps and download VSCode"

    - script: |
        export DISPLAY=:99
        export VSCODE_E2E_DOWNLOAD_PATH=$(VSCODE_E2E_DOWNLOAD_PATH)
        npm run test:create
      displayName: "Run Playwright Electron UI Tests"
      env:
        CI: true
        DISPLAY: ":99"
        VSCODE_E2E_DOWNLOAD_PATH: $(VSCODE_E2E_DOWNLOAD_PATH)
        ELECTRON_DISABLE_SANDBOX: "1"
        BUILD_ARTIFACT_STAGING_DIRECTORY: $(Build.ArtifactStagingDirectory)
        continueOnError: true
    
    - script: |
        pwd
        ls -al
        ls -al images-linux || true
      displayName: "Debug: List workspace and images-linux"

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: 'images-linux'
        artifactName: 'screenshots'
        publishLocation: 'Container'
      displayName: 'Publish Screenshots'